server:
#  port: 8081
  port: 0

spring:
  application:
#    name: first-service
    name: MY-FIRST-SERVICE

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
